---
- hosts: "{{ target_host }}"
  vars:
   - ansible_network_os: vyos
   - ansible_connection: network_cli

  tasks:
   - name: Change Host Name
     vyos_config:
      lines:
       - set system host-name {{ change_hostname }}
       
