---
- hosts: all
  vars:
   - ansible_user: vyos
   - ansible_ssh_pass: 131296
   - ansible_network_os: vyos
   - ansible_connection: network_cli

  tasks:
   - name: Change Host Name
     vyos_config:
      lines:
       - set system host-name R1
       
